We have officially hit the road! Parsing seems to work for most part.
SPENT ALL DAY PULLING HAIR OUT AT WORK OVER PARSER NOT PICKING UP LEFTBRACES BECAUSE OF A SINGLE EVIL WHITESPACE. thank god that's over"
error: pathspec 'mWe have officially hit the road! Parsing seems to work for most part. SPENT ALL DAY PULLING HAIR OUT AT WORK OVER PARSER NOT PICKING UP LEFTBRACES BECAUSE OF A SINGLE EVIL WHITESPACE. thank god that's over